In [46]:
import numpy as np
import pandas as pd

raw_crime_anal_police = pd.read_csv("2015_crime_in_seoul.csv", thousands=',', encoding='euc-kr').dropna()

raw_crime_anal_police

     구분  죄종 발생검거      건수
0    중부  살인   발생     2.0
1    중부  살인   검거     2.0
2    중부  강도   발생     3.0
3    중부  강도   검거     2.0
4    중부  강간   발생   105.0
..   ..  ..  ...     ...
305  수서  강간   검거   124.0
306  수서  절도   발생  1439.0
307  수서  절도   검거   666.0
308  수서  폭력   발생  1819.0
309  수서  폭력   검거  1559.0

[310 rows x 4 columns]

In [47]:
crime_anal_police = pd.DataFrame(columns=["살인발생", "살인검거", "강도발생", "강도검거", "강간발생", "강간검거", "절도발생", "절도검거", "폭력발생", "폭력검거"], index= raw_crime_anal_police["구분"].unique())

crime_anal_police.head(10)

    살인발생 살인검거 강도발생 강도검거 강간발생 강간검거 절도발생 절도검거 폭력발생 폭력검거
중부   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
종로   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
남대문  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
서대문  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
혜화   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
용산   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
성북   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
동대문  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
마포   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
영등포  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [49]:
print(raw_crime_anal_police["죄종"][0])
for idx, row in raw_crime_anal_police.iterrows():
    # print(row["구분"], row["죄종"], row["발생검거"], row["건수"])
    crime = row["죄종"] + row["발생검거"]
    area = row["구분"]
    data = row["건수"]
    if area in crime_anal_police.index and crime in crime_anal_police.columns :
        crime_anal_police.loc[area, crime] = data

crime_anal_police.head(10)

살인

     살인발생  살인검거  강도발생  강도검거   강간발생   강간검거    절도발생   절도검거    폭력발생    폭력검거
중부    2.0   2.0   3.0   2.0  105.0   65.0  1395.0  477.0  1355.0  1170.0
종로    3.0   3.0   6.0   5.0  115.0   98.0  1070.0  413.0  1278.0  1070.0
남대문   1.0   0.0   6.0   4.0   65.0   46.0  1153.0  382.0   869.0   794.0
서대문   2.0   2.0   5.0   4.0  154.0  124.0  1812.0  738.0  2056.0  1711.0
혜화    3.0   2.0   5.0   4.0   96.0   63.0  1114.0  424.0  1015.0   861.0
용산    5.0   5.0  14.0  14.0  194.0  173.0  1557.0  587.0  2050.0  1704.0
성북    2.0   2.0   2.0   1.0   86.0   71.0   953.0  409.0  1194.0  1015.0
동대문   5.0   5.0  13.0  13.0  173.0  146.0  1981.0  814.0  2548.0  2227.0
마포    8.0   8.0  14.0  10.0  294.0  247.0  2555.0  813.0  2983.0  2519.0
영등포  14.0  12.0  22.0  20.0  295.0  183.0  2964.0  978.0  3572.0  2961.0

In [ ]:
import requests

client_id = "xq5f66ddpg"
client_secret = "8hOej5iHqSGJ1xMBqVx14BInDBtwz32rAHlzQn2j"

url = "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode"

headers = {
    "X-NCP-APIGW-API-KEY-ID": client_id,
    "X-NCP-APIGW-API-KEY": client_secret
}

params = {
    "query": "서울특별시 중구 세종대로 110"
}

response = requests.get(
    url,
    headers=headers,
    params=params
)

result = response.json()

print(result)

{'error': {'errorCode': '200', 'message': 'Authentication Failed', 'details': 'Invalid authentication information.'}}